# Implementing backpropagation

![information](img\information.png)

## Backpropagation exercise
Now you're going to implement the backprop algorithm for a network trained on the graduate school admission data. You should have everything you need from the previous exercises to complete this one.

Your goals here:

- Implement the forward pass.
- Implement the backpropagation algorithm.
- Update the weights.

In [22]:
import numpy as np
from data_prep import features, targets, features_test, targets_test

np.random.seed(21)

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # TODO: Calculate the output
        hidden_input = np.dot(x, weights_input_hidden)
        hidden_output = sigmoid(hidden_input)
        output = sigmoid(np.dot(hidden_output, weights_hidden_output ))

        ## Backward pass ##
        # TODO: Calculate the network's prediction error
        error = y - output

        # TODO: Calculate error term for the output unit
        output_error_term = error * output * (1 - output)

        ## propagate errors to hidden layer

        # TODO: Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(weights_hidden_output,output_error_term)
        
        # TODO: Calculate the error term for the hidden layer
        hidden_error_term = hidden_error * hidden_output * (1 - hidden_output)
     
        # TODO: Update the change in weights
        del_w_hidden_output += output_error_term * hidden_output
        del_w_input_hidden += hidden_error_term * x[:,None]

    # TODO: Update weights  (don't forget to division by n_records or number of samples)
    weights_input_hidden += learnrate * del_w_input_hidden / n_records
    weights_hidden_output += learnrate * del_w_hidden_output / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))


Train loss:  0.27630002065852294
Train loss:  0.27487280940102665
Train loss:  0.2734814690053808
Train loss:  0.27212535119812675
Train loss:  0.27080379729958337
Train loss:  0.2695161402601928
Train loss:  0.2682617065761968
Train loss:  0.26703981808591765
Train loss:  0.2658497936485804
Train loss:  0.26469095070807397
Prediction accuracy: 0.425


In [11]:
weights_input_hidden

array([[-0.02114952, -0.04542027],
       [ 0.42536536, -0.51307962],
       [ 0.30429765, -0.69853181],
       [-0.08410102, -0.09573925],
       [ 0.46048191, -0.00511942],
       [-0.25038943,  0.56082608]])

In [12]:
weights_hidden_output

array([ 0.65705345, -0.28208147])

In [8]:
weights_input_hidden

array([[-0.02121502, -0.04539638],
       [ 0.42531106, -0.51306245],
       [ 0.30430255, -0.69853556],
       [-0.08404448, -0.09576411],
       [ 0.46056218, -0.00515531],
       [-0.25033867,  0.5608052 ]])

In [ ]:
#####Implementation of Backpropagation#######
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
#weights_input_hidden = (6,2)
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
#weights_hidden_output.shape = (2,)
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

for e in range(epochs):
    
    #delta weights from inputs to the two hidden units
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    
    #delta weights from hidden units to the single output unit
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    
    #iterates over the features and targets, 
    #assigning features to x and targets to y
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # DONE: CalculateS the output
        hidden_input = np.dot(x, weights_input_hidden)#input to hidden units
        hidden_output = sigmoid(hidden_input)#output of hidden units
        
        #output of final output unit
        output = sigmoid(np.dot(hidden_output, weights_hidden_output))

        ## Backward pass ##
        # DONE: Calculate the network's prediction error
        error = y - output #error = difference between predited output and target

        # DONE: Calculate error term for the output unit
        #output * (1 - output) = sigmoid_prime, derivative of the output
        output_error_term = error * output * (1 - output)
        

        ## propagate errors to hidden layer

        # DONE: Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(weights_input_hidden, output_error_term)
        
        # DONE: Calculate the error term for the hidden layer
        hidden_error_term = hidden_error * hidden_output * (1-hidden_output)
        
        # DONE: Update the change in weights
        del_w_hidden_output += output_error_term*output
        del_w_input_hidden += hidden_error_term*np.array(x, ndmin=2).T

    # DONE: Update weights
    #adds the product of learning rate, change in weights from adding negative gradients, and 
    #takes the average by dividing by total number of data points or number of records
    weights_input_hidden += learnrate* del_w_input_hidden/n_records
    weights_hidden_output += learnrate * del_w_hidden_output/n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))
